[package]
name = "rough"
version = "0.1.0"
edition = "2021"

[dependencies]
async-executor = "1.6.0"
async-lock = "3.1.0"
event-listener = "3.1.0"
fancy = "0.3.1"
futures-lite = "2.0.1"
nom = "7.1.3"
nom_locate = "4.2.0"
num_cpus = "1.16.0"
